/**
 * @file Automatically generated by barrelsby.
 */

export * from "./controller/base-controller.controller";
export * from "./module/constants";
export * from "./module/json-api.module";
export * from "./resource/base-resource";
